source "http://rubygems.org"

gem "sinatra"
gem "sinatra_more", :require => "sinatra_more/markup_plugin"
gem "thin"
gem "haml"
gem "sinatra-twitter-bootstrap", :require => "sinatra/twitter-bootstrap"
gem 'sinatra-assetpack', :require => 'sinatra/assetpack'
